### ISSUE TITLE
Add all existing packages to package list

### ISSUE THREAD

**Issue by missinglink** [pelias/ownership#2]
@pelias/owners please add any packages you have created for pelias to `example-packages.json` and run `./ownership-all` so that everyone can publish to them.

If there is a package you don't want to add because it's not directly related to the project or because it was done in personal time then please discuss with me offline.

**Comment by orangejulius** [comment]
I've added [pelias-fuzzy-tester](https://www.npmjs.com/package/pelias-fuzzy-tester) and run it once with just that package so everyone is a collaborator. I've also added myself so if someone else who is already a collaborator could re-run the script to add me that would be appreciated :)

**Comment by missinglink** [comment]
```
$ node ownership-all 
adding 4 owners to pelias-admin-lookup, pelias-api, pelias-config, pelias-dbclient, pelias-esclient, pelias-fuzzy-tester, pelias-geonames, pelias-hierarchy-lookup, pelias-init, pelias-logger, pelias-model, pelias-openaddresses, pelias-openstreetmap, pelias-query, pelias-schema, pelias-suggester-pipeline, pelias-tiger, openstreetmap-stream, osmium-stream, geonames-stream, prop-stream, shapefile-stream, quattroshapes-pipeline, line-interpolate-points, polygon-lookup, pbf2json, geopipes-elasticsearch-backend, fences, fences-builder, fences-slicer, geocodejson-stream
Adding users to: pelias-admin-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-api
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-config
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-dbclient
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-esclient
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-fuzzy-tester
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-geonames
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-hierarchy-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-init
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-logger
err 1: unable to add missinglink - are you sure the module pelias-logger exists and is published?
Adding users to: pelias-model
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-openaddresses
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-openstreetmap
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-query
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-schema
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: pelias-suggester-pipeline
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: openstreetmap-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: osmium-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: geonames-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: prop-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: shapefile-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: line-interpolate-points
err 1: unable to add missinglink - are you sure the module line-interpolate-points exists and is published?
Adding users to: polygon-lookup
err 1: unable to add missinglink - are you sure the module polygon-lookup exists and is published?
Adding users to: pbf2json
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: geopipes-elasticsearch-backend
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: fences
err 1: unable to add missinglink - are you sure the module fences exists and is published?
Adding users to: fences-builder
err 1: unable to add missinglink - are you sure the module fences-builder exists and is published?
Adding users to: fences-slicer
err 1: unable to add missinglink - are you sure the module fences-slicer exists and is published?
Adding users to: geocodejson-stream
err 1: unable to add missinglink - are you sure the module geocodejson-stream exists and is published?
```

cc/ @sevko re: `pelias-logger`, `line-interpolate-points`, `polygon-lookup`
cc/ @dianashk re: `fences`, `fences-builder`, `fences-slicer`, `geocodejson-stream`

please run `$ node ownership-all` from your account to give everyone `npm publish` access, it will be easier if you first edit `example-packages.json` to only have the ones mentioned, else it will fail lots.

**Comment by sevko** [comment]
Heya, here we go:

```
adding 4 owners to pelias-logger, line-interpolate-points, polygon-lookup
Adding users to: pelias-logger
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: line-interpolate-points
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen 
Adding users to: polygon-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen
```

I don't think I have access rights to the repo any longer, so I can't push the commit that added the three packages to `example-packages.json`. Either give me perms or add the following yourself:

```
  "pelias-logger",
  "line-interpolate-points",
  "polygon-lookup"
```

**Comment by riordan** [comment]
Thanks @sevko!

@stephenkhess: could you register an account on [npm](https://www.npmjs.com/) and send your ID so we can close this ticket.

Anyone else who should be in here?

**Comment by trescube** [comment]
just signed up, username is:

2foo2fighters

**Comment by orangejulius** [comment]
adding 5 owners to pelias-admin-lookup, pelias-api, pelias-config, pelias-dbclient, pelias-esclient, pelias-fuzzy-tester, pelias-geonames, pelias-hierarchy-lookup, pelias-init, pelias-logger, pelias-model, pelias-openaddresses, pelias-openstreetmap, pelias-query, pelias-schema, pelias-suggester-pipeline, openstreetmap-stream, osmium-stream, geonames-stream, prop-stream, shapefile-stream, line-interpolate-points, polygon-lookup, pbf2json, geopipes-elasticsearch-backend, fences, fences-builder, fences-slicer, geocodejson-stream, pelias-logger, line-interpolate-points, polygon-lookup
Adding users to: pelias-admin-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-api
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-config
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-dbclient
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-esclient
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-fuzzy-tester
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-geonames
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-hierarchy-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-init
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-logger
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-model
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-openaddresses
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-openstreetmap
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-query
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-schema
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pelias-suggester-pipeline
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: openstreetmap-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: osmium-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: geonames-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: prop-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: shapefile-stream
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: line-interpolate-points
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: polygon-lookup
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: pbf2json
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: geopipes-elasticsearch-backend
✓ missinglink ✓ dianashk ✓ riordan ✓ julian_mapzen ✓ 2foo2fighters 
Adding users to: fences
err 1: unable to add missinglink - are you sure the module fences exists and is published?

Ok we are getting there. @dianashk run this on the fences repos when you get a chance and we should be done.

**Comment by dianashk** [comment]
Completed successfully, so I think we should be all set. Someone please verify and let me know if this can be closed.

**Comment by orangejulius** [comment]
I think we're done with the exception of pelias/whosonfirst and pelias/wof-admin-lookup, which haven't been published as NPM modules yet. They might not need to be...

**Comment by orangejulius** [comment]
This is all done. When we publish `pelias-whosonfirst` we should add that package here, but until then there's nothing else to do.
